### PR TITLE
Added register View and logic

### PR DESCRIPTION
**Pull request by BlaiseMahoro**

### CODE REVIEW

**Comment by B1Dobbs** [comment]
Hey Blaise! Just tried to register and got the following error: 
image

Also, the registration pages shouldn't extend the base_generic page because we don't want to see the navigation bar.

**Comment by BlaiseMahoro** [comment]
1.Run python manage.py migrate.
2. I didn't know that. I just used whatever existed. We can easily change
that.
Thanks!
Blaise

**Comment by B1Dobbs** [comment]
Gotcha! Thought you were pushing the migrations. I'll do that.

**Comment by BlaiseMahoro** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Pull request merged**
